Feature/sa 51 wishlists service
Shchoholiev/shopping-assistant-api pull request #4
Opened 2023-10-09 10:51 UTC by cuqmbr

2023-10-10 04:24 UTC, cuqmbr commented on ShoppingAssistantApi.Api/ApiExtentions/GraphQlExtention.cs
>                  .AddTypeExtension<AccessMutation>()
test comment

2023-10-10 14:03 UTC, Mikhail-Beloded requested changes

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Wishlist.cs
> +    public required ObjectId UserId { get; set; }
You don't need this. You already have property for user as CreatedById from EntityBase

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Message.cs
> +    public ObjectId? WishlistId { get; set; } = null;
In ER diagram it's not null

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Enums/MessageRoles.cs
> +    User = 0,
The same values of constants (0 and 0)

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Wishlist.cs
> +    public required string Name { get; set; }
Add spaces between properties

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Message.cs
> +    public required string Role { get; set; }
Add spaces between properties

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Wishlist.cs
> +    public ICollection<Message>? Messages { get; set; } = null;
= null part unnecessary

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Domain/Entities/Message.cs
> +    public ObjectId? WishlistId { get; set; } = null;
= null part unnecessary

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Api/Mutations/WishlistsMutation.cs
What about to create query for retrieving data such as getting wishlists from database?

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Application/Models/CreateDtos/WishlistCreateDto.cs
> +    public required string FirstMessageText { get; set; }
spacing again

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Application/Models/Dtos/MessageDto.cs
> +    public required string Text { get; set; }
spacing again

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Application/Models/Dtos/WishlistDto.cs
> +    public required string Type { get; set; }
spacing again

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Infrastructure/Services/WishlistsService.cs
> +    private readonly IMessagesRepository _messagesRepository;
spacing

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Infrastructure/Services/WishlistsService.cs
> +        newWishlist.Name = $"{newWishlist.Type} Search";
In this way you will have wishlists only with 2 types of names

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Infrastructure/Services/WishlistsService.cs
> +        var relatedWishlistPage = await _wishlistsRepository.GetPageAsync(1, 1, x => x.Id == wishlistObjectId && x.CreatedById == GlobalUser.Id, cancellationToken);
avoid this and create in WishListRepository GetWishList method for getting wishlists and put expression as parameter to make that method more flexible

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Persistance/PersistanceExtentions/DbInitialaizer.cs
>      private readonly IUserManager _userManager;
bring spacing back

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Tests/Tests/WishlistsTests.cs
split your testing method for both mutations

2023-10-10 14:03 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Tests/Tests/WishlistsTests.cs
Also add testing methods with invalid data

2023-10-11 06:09 UTC, cuqmbr commented on ShoppingAssistantApi.Api/Mutations/WishlistsMutation.cs
will be added in [SA-53](https://shchoholiev.atlassian.net/browse/SA-53?atlOrigin=eyJpIjoiZjc2YzVjZWVkMDU0NGFkYjk3OTRlMmU4NzQ0Mzc5YTUiLCJwIjoiaiJ9) this week

2023-10-11 09:41 UTC, cuqmbr commented on ShoppingAssistantApi.Infrastructure/Services/WishlistsService.cs
> +        newWishlist.Name = $"{newWishlist.Type} Search";
Yes, by default. Name will be changed later automatically based on user messages or manually by the user.

2023-10-11 16:28 UTC, Mikhail-Beloded requested changes

2023-10-11 16:28 UTC, Mikhail-Beloded commented on ShoppingAssistantApi.Api/Queries/WishlistsQuery.cs
> +
Add here request for retrieving single personal wishlist. GetPersonalWishListAsync()

2023-10-11 18:08 UTC, Mikhail-Beloded approved these changes

2023-10-11 18:08 UTC, merged